### ISSUE TITLE
cannot use it with livolo remote rf switch 

### ISSUE THREAD

**Issue by hackruu** [radinsky/broadlink-http-rest#1]
It learns rf remote button, but cannot replay command.
When i use IR remote, everything is fine.

Does it support RF at all?

**Comment by radinsky** [comment]
Yes, tested and working fine on many RF switched and plugs. Can you see the activity led on RM flashing when you sending your commands?

**Comment by hackruu** [comment]
yes, it's looks like code is received partial or something like that. becase when i replay recorded signal 20 or 30 times, it works and my lights are on, then i need 20 or 30 times again.
at the same time stock broadlink application learns code well and turns on/off from first try.

**Comment by radinsky** [comment]
What I found when learned my switches, that's is better to do like "short click" on remote's button. Otherwise it sending very long command that probably harder to save or recall after..

**Comment by Oliv3rDog** [comment]
When I learned my Livolo remotes, I usually learned 10 times each button and stored those codes to try each one and see what was the best one...
Another alternative is loading a cloud livolo remote (there are plenty of them on the add remote search button top right) and use the method described at the end of documentation on broadlink switch section on HA website.
That way you step over the learning part and use your E-Control database to create the base64 codes for HA...
https://home-assistant.io/components/switch.broadlink/

**Comment by hackruu** [comment]
yes, i finished by downloading template from cloud to iphone, download app database over openssh(my iphone is jailbroken) and extracting command from there. still, i'm not happy about this :) proper solution will be in generating remotes code, not sniffing it.

**Comment by radinsky** [comment]
You're not sniffing them, you're learning the rf codes and replaying them later. There's a lot of them, very different and very custom.
