### ISSUE TITLE
[Commands] in Settings.ini

### ISSUE THREAD

**Issue by lmfilio** [radinsky/broadlink-http-rest#12]
Is there anything I need to put into the [Commands] of the Settings.ini to make a sendCommand work?

I tried testing but I am receiving a log of "timeout":

pi@raspberrypi:~/rm3/broadlink-http-rest $ sudo python server.py 
Starting broadlink-rest server on port 80 ...
127.0.0.1 - - [07/Jun/2018 19:06:46] "GET /sendCommand/test HTTP/1.1" 200 -
127.0.0.1 - - [07/Jun/2018 19:06:56] Request timed out: timeout('timed out',)

Appreciate the help.

**Comment by uudruid74** [comment]
You need to use learnCommand to learn the command you want to send. And you don't need root.

**Comment by lmfilio** [comment]
I tried entering this in a browser - https://localhost/learnCommand/aircon

Here is the response: 

pi@raspberrypi:~/rm3/broadlink-http-rest $python server.py 
Starting broadlink-rest server on port 80 ...
127.0.0.1 - - [08/Jun/2018 10:58:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2018 10:59:01] "GET /learnCommand/test HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2018 10:59:11] Request timed out: timeout('timed out',)
127.0.0.1 - - [08/Jun/2018 10:59:53] "GET /learnCommand/aircon HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2018 11:00:03] Request timed out: timeout('timed out',)

Do I need to press a sample IR button in between the command and the RTO?

**Comment by uudruid74** [comment]
Yes, it is timing out waiting on you to push a button.  If you are using the blackbean, you'll see the LED go white.  Not sure how other devices are set.
