### ISSUE TITLE
Learn command problem 

### ISSUE THREAD

**Issue by TPponmat** [radinsky/broadlink-http-rest#15]
I got this massage
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

after learn command

**Comment by radinsky** [comment]
Can you tell me how to reproduce this issue at my setup?
Are you trying to learn the non-exist command in settings.ini?
Which broadlink do you have? rm2/bb?

**Comment by uudruid74** [comment]
@TPponmat Are you using an HTTP POST or GET?  A POST may be looking for JSON formatted data.  Are you sending anything to it in the POST body?

**Comment by radinsky** [comment]
@TPponmat any chance you can update if solved?
