### ISSUE TITLE
Interested in Advanced Features?

### ISSUE THREAD

**Issue by uudruid74** [radinsky/broadlink-http-rest#18]
I've been running my personal "advanced macro" branch for awhile now and just merged it to my "master".  It contains a number of nifty features, such as being able to toggle a status variable to keep track of a device's status when the remote would normally toggle.  Or you can ping a device to see if it's online before you turn it on.   Conditional logic and loops are supported, external shell commands, parameter substitution, wake on lan, etc.

Rather than just rest API to send an IR command, it's more of a home automation middle-ware that sits between apps like IFTTT and your IR devices, capable of rather complex decisions.  The existing settings file format remains the same.

Let me if you are interested and I can issue a PR, or just check out my repo and give it a whirl.

**Comment by radinsky** [comment]
It looks very nice, great job!

Regarding the PR, I think it will better to separate the kind of "low level" API for the basic functionality (http to broadlink) and maybe to add external extensions as packages for ifttt, google home and etc.

So it will be easy to "import" the extended functionality but you can keep clean the basic API.

**Comment by uudruid74** [comment]
I'll have to consider how to modularize things, but the macro parsing and such are pretty fundamental.  Next I plan on adding psuedo-variables for time of day and maybe GPIO control and look into threading it.  Maybe I'll rename it, keeping a "based on code by ..." line since I imagine its going to be changing quite a bit
