### ISSUE TITLE
Multiple RM Pro

### ISSUE THREAD

**Issue by TootToot168** [radinsky/broadlink-http-rest#2]
How to add more than 1 RM Pro in the settings.ini?
How to send command to only 1 of the RM Pro declared in settings.ini?

**Comment by radinsky** [comment]
No, currently only one RM per settings.ini
Will add multiple support within few days.

**Comment by TootToot168** [comment]
For those interested and incase the multiple support has issues or bugs when included. i tried running multiple instances of this on different port with each instance using different settings.ini for each RM PRO. It works well.
