### ISSUE TITLE
'module' object has no attribute 'SIGUSR1'

### ISSUE THREAD

**Issue by Harel-M** [radinsky/broadlink-http-rest#21]
Hi, when running the script I get the following error:

Traceback (most recent call last):
  File "server.py", line 523, in <module>
    signal.signal(signal.SIGUSR1,SigUsr1)
AttributeError: 'module' object has no attribute 'SIGUSR1'

If I'm deleting line 523 the script is working... but I guess there should be better solution.
I'm working on Windows 10. Maybe I'm missing any dependency package?

Thanks,

**Comment by radinsky** [comment]
@uudruid74 any chance you can take a look on it?

**Comment by uudruid74** [comment]
Yes, SIGUSR1 is used to restart the server when a config has been changed.  I guess Windows doesn't support it.  I'll try to make it conditional
