### ISSUE TITLE
On/Off commands not sent

### ISSUE THREAD

**Issue by Harel-M** [radinsky/broadlink-http-rest#22]
I think there is a mistake in line 135:
result = getStatus(realcommandName, deviceName)

it should be:
result = sendCommand(commandName, deviceName)

currently any command with 'on' or 'off' in the name are not sent....

**Comment by radinsky** [comment]
@Harel-M 
Could you please provide a command you're trying to use (full url) I will try to reproduce it in my environment?

**Comment by Harel-M** [comment]
Example:
http://xx.xx.xx.xx:8000/RM_Livingroom/sendCommand/TVon
but anything with on or off in the command name (that makes the condition in line 127 true) will behave the same.

It prints that the command is sent, but nothing happens (the amber led is not blinking on the device).

After doing the above change to line 135 it works (I don't see anywhere in the original code calling the sendCommand function)

**Comment by radinsky** [comment]
ok, I pushed a fix, any chance you can pull the recent change and check if it fixed the issue (i will be able to test it only tomorrow)? thanks!

**Comment by Harel-M** [comment]
Hi, I could only check it today... now it's working 👍 

Thanks :)

**Comment by uudruid74** [comment]
May have been my fault on that
