### ISSUE TITLE
RM3 Mini support?

### ISSUE THREAD

**Issue by tomerrr** [radinsky/broadlink-http-rest#26]
hi,
i was able to learn a command with RM3 Mini, but everytime i try to send it I get
"GET /sendcommand/lampon HTTP/1.1" 200 -
	Failed
the Autodetect function recognized the mini as 
[BroadlinkRM2]
IPAddress = 10.0.0.30
MACAddress = xx:xx
Device = 0x2737
Timeout = 10
Type = RM2

I've also tried changing device type to 0x27c2 which according to python-broadlink script is the identifier for RM3 Mini - didn't help though .

is it supposed to work with RM3 Mini as well?

**Comment by radinsky** [comment]
RM3 Mini supported as well.

Can you post your settings.ini and url that you're using?

**Comment by tomerrr** [comment]
```
[General]
Timeout = 4
serverPort = 8008
serverAddress = 10.0.0.37

[Commands]
lampon = b9cdfad2f36ce185e96b48bd68eab9466c200de58a7170512b838afc5bac71c6727c33c0db4323a9fed75292a02fa6385a7ac242b43c76ab7bd0baa5beed289e275fcd5c4452b6410fe796f44d97bce361d98dcf2935e09dfcea9abca5c21895e32bd546fb38a0831034b1d26427fd1f1137d10f0b77cbdaa95484046acc8204ce6ac54e20804a601d2045ba3a4a411ec6f968da16477fac312309d467666cad70b7114f00041e4420daad67df5e1ecb9bff4471f7180272aa64f4b7d1f18681e2d115eb20356df46ddda3623295ba9030ad7fde6449ad4be633067e62b848ce26f96f0e0a8b6ecc9c62cfaee8f94772c11feecb8c2b209c27fcc2929a734aa28ecaf1e5d0d9fa8369979c3410f36b0ab38a711dd5c94120022bc1f8c045ce6bd2d2d576f9b3b867704986aef89797f9390c10ec990b5d741784dae1a2666cd38a8a5df13e1e2bc029682c27df11957252ccd32168dc5451ac33d2aab21323f04bdfbb6b4dda9874fb8adb5fe6ea7613a1b25040f7e6e6fd31a8044e02a6161f4f641c9fd78907cf1a9e1f7f42560ae5f64298a175e530f4e374895b42ea36e2d8c260cc51e8debc12c3dc3044f23f4f

[BroadlinkRM2]
IPAddress = 10.0.0.30
MACAddress = xx:xx
Device = 0x2737
Timeout = 10
Type = RM2
```

i use http://10.0.0.37:8008/sendcommand/lampon 
to send commands

**Comment by tomerrr** [comment]
ok i think i found the problem -
sendcommand doesn't work , while sendCommand does

**Comment by radinsky** [comment]
Yes, exactly, all commands are case-sensitive
