### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 after a new learn 

### ISSUE THREAD

**Issue by tomerrr** [radinsky/broadlink-http-rest#31]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
although i do see a new code in settings.ini for the learned command

using POST command on a browser to RM3 Mini

**Comment by radinsky** [comment]
Strange, can you please provide more details on your environment I would like to reproduce it?

**Comment by tomerrr** [comment]
it's running on Raspberry Pi Zero W / Raspbian stretch 9.11, 
kernel raspberrypi 4.19.66+
Python 2.7.13
the browser used for the learn command is Firefox 68
also, I've upgraded to the newer server.py with the listCommand option

**Comment by radinsky** [comment]
Which python version and python-broadlink used?

**Comment by tomerrr** [comment]
Python 2.7.13 ,
python-broadlink 0.9

**Comment by radinsky** [comment]
Please take a look here: https://github.com/radinsky/broadlink-http-rest/issues/30#issuecomment-515679879
