### ISSUE TITLE
Sky Q Black

### ISSUE THREAD

**Issue by marcodesantis71** [radinsky/broadlink-http-rest#33]
Hi,
I tried to acquire the sky q remote control.

But the code is not acquired.

Where am I wrong? I acquired other remote controls without problems.

**Comment by radinsky** [comment]
I'm not familiar with Sky Q Black, which protocol used for remote? is it rf? ir? or maybe something else?

**Comment by marcodesantis71** [comment]
HI,

ops. 

Sorry, I forgot to close the issue.

I solved it by setting the Sky remote to IR instead of BT.
