### ISSUE TITLE
RM Pro temperature

### ISSUE THREAD

**Issue by cnliri1** [radinsky/broadlink-http-rest#5]
Hello,

Right now the remote control function works well.
can you provide a guide that without A1 how to record temperature by RM PRO in domoticz so that can be display in homekit?
i find a new virtual temp sensor named rm already created in domoticz but the temperature keeps 0.
if only some setting needs configured or another python needed?
thanks!

**Comment by radinsky** [comment]
Hey, 

sorry not familiar with domoticz, but I think you can figure it out by polling the RM Pro temperature by using: 
`http://localhost:8080/getStatus/temperature`
Do you know which format required for the "virtual temp sensor" you mentioned?

**Comment by thunder2k** [comment]
> Hey,
> 
> sorry not familiar with domoticz, but I think you can figure it out by polling the RM Pro temperature by using:
> `http://localhost:8080/getStatus/temperature`
> Do you know which format required for the "virtual temp sensor" you mentioned?

Hi, I'm trying the following with my RM Pro (other commands work):
`http://localhost:8080/getStatus/temperature`
and I'm getting:
`{ "error": "Failed: Cannot get temperature" }`

Any advice?

Thanks!
