### ISSUE TITLE
Multiple RM support

### ISSUE THREAD

**Issue by nicx** [radinsky/broadlink-http-rest#6]
Hi,

I have 3 BlackBeans and I would like to use all of them with a single instance running of the python server. As of now I have to run 3 instances. Could you extend your application so its usable for this szenario?

If you use the name of the device in the settings.ini for addressing each device, all broadlink devices could be accessed in that way:

http://localhost:8080/Broadlink1/getStatus/
http://localhost:8080/Broadlink2/getStatus/
http://localhost:8080/BroadlinkXYZ/getStatus/
http://localhost:8080/A1/temperature/
etc.

This would be great :)

**Comment by uudruid74** [comment]
I have this implemented but only have 1 device to test.  I tested by giving the same device two names and I can access it by either.  It's still compatible with the old URLs as well.  I did not (yet) make a provision for having separate Command sections per device, so if you need that, you'll have to make your command names creative for awhile.  

~~I'll have my version on my github soon.~~  Can you grab it off my github and test it before I make a PR?

https://github.com/uudruid74/broadlink-http-rest

Best way to configure it will be to just remove your device sections.  It's supposed to autodiscover the devices and write the config file for you.  Sections/Devices will be named by their hostnames.  If you don't autoconfigure, you need to have the type (A1, RM, etc) as the last two characters of the device name or specify it with "Type = ", latter preferred.

**Comment by uudruid74** [comment]
This is now implemented as of #13
